# docker-compose.yml
version: '3'
services:
    fastapi:
        image: fastapi
        build:
            context: .
        ports:
          - 8000:80
        volumes:
          - ./app:/INTERVIEW_PROJECT/app

    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=developer
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        ports:
            - "25100:6379"
        command: redis-server --save ""

volumes:
    postgres-data:
        driver: local